[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
one = "base"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "closed-non-crossing-serifed"
five = "upright-arched-serifed"
six = "closed-contour"
seven = "straight-serifed-crossbar"
eight = "two-circles"
nine = "closed-contour"
zero = "unslashed"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "hex-high"
underscore = "high"
caret = "high"
ascii-grave = "raised-inverse-comma"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "slanted-open"
ampersand = "upper-open"
at = "threefold-tall"
dollar = "slanted-through"
cent = "slanted-through"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "corner-flat-hooked"
pilcrow = "high"
partial-derivative = "straight-bar"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.variants.italic]
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.variants.oblique]
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"